<?php

namespace Container20IccUZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MFeDsQ0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mFeDsQ0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mFeDsQ0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userPasswordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'userTypeRepository' => ['privates', 'App\\Repository\\UserTypeRepository', 'getUserTypeRepositoryService', true],
        ], [
            'entityManager' => '?',
            'userPasswordHasher' => '?',
            'userTypeRepository' => 'App\\Repository\\UserTypeRepository',
        ]);
    }
}
