<?php

namespace ContainerVRLraoa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3W8_P7qService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3W8.P7q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3W8.P7q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ProjectRepo' => ['privates', 'App\\Repository\\ProjectRepository', 'getProjectRepositoryService', true],
        ], [
            'ProjectRepo' => 'App\\Repository\\ProjectRepository',
        ]);
    }
}
