project_main_home:
   path: /
   controller: App\Controller\HomeController::index

######################################################### USER ####################################################

project_registery:
   path: /registerlink
   controller: App\Controller\RegistrationController::registerlink

project_regist_makers:
   path: /register/complete
   controller: App\Controller\RegistrationController::register

project_regist_votant:
   path: /register/rapide
   controller: App\Controller\RegistrationController::register

project_log:
   path: /login
   controller: App\Controller\SecurityController::login

project_logout:
   path: /logout
   controller: App\Controller\SecurityController::logout

project_user:
   path: /user/{idUser}
   controller: App\Controller\UserController::show
   requirements:
     idArticle: '\d+'
project_rech:
   path: /api_data
   controller: App\Controller\ApiController::getData

########################################################### MUSE #####################################################

project_create_project:
   path: /creation_projet
   controller: App\Controller\ProjectController::create

project_create_project_middle:
   path: /creation_projet_part2/{idProject}
   controller: App\Controller\ProjectController::create2
   requirements:
     idArticle: '\d+'

project_project_confirmation:
   path: /confirmaion/{idProject}
   controller: App\Controller\ProjectController::Confirmation
   requirements:
     idArticle: '\d+'
