project_main_home:
   path: /
   controller: App\Controller\HomeController::index


project_log:
   path: /login
   controller: App\Controller\SecurityController::login

project_registery:
   path: /registerlink
   controller: App\Controller\RegistrationController::registerlink

project_regist_makers:
   path: /register/complete
   controller: App\Controller\RegistrationController::register

project_regist_votant:
   path: /register/rapide
   controller: App\Controller\RegistrationController::register