<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZAoUvm4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZAoUvm4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZAoUvm4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZAoUvm4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZAoUvm4\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZAoUvm4',
    'container.build_id' => 'dd734ab1',
    'container.build_time' => 1648122606,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZAoUvm4');
