<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container20IccUZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container20IccUZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container20IccUZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container20IccUZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container20IccUZ\App_KernelDevDebugContainer([
    'container.build_hash' => '20IccUZ',
    'container.build_id' => 'fd4c579e',
    'container.build_time' => 1648114804,
], __DIR__.\DIRECTORY_SEPARATOR.'Container20IccUZ');
