<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY7JFmOB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY7JFmOB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY7JFmOB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY7JFmOB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY7JFmOB\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y7JFmOB',
    'container.build_id' => '97697267',
    'container.build_time' => 1648201483,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY7JFmOB');
